"builtin.module"() ({
  "tpu_schedule.kernel"() <{sym_name = "inkling_rpa_decode", target = "tpu7x", vmem_capacity_bytes = #builtin.int<2097152>, smem_capacity_bytes = #builtin.int<65536>}> ({
  ^bb0(%0: !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %1: !tpu_schedule.buffer<memref<32x16x4x32xbf16>, #tpu_schedule.shape<["P", "S", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>, #builtin.int<3>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %2: !tpu_schedule.buffer<memref<32x16x4x32xbf16>, #tpu_schedule.shape<["P", "S", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>, #builtin.int<3>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %3: !tpu_schedule.buffer<memref<4x8xi32>, #tpu_schedule.shape<["B", "MP"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %4: !tpu_schedule.buffer<memref<4xi32>, #tpu_schedule.shape<["B"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<[""]>, #tpu_schedule.layout<[#builtin.int<0>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %5: !tpu_schedule.buffer<memref<4x128xbf16>, #tpu_schedule.shape<["H", "L"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %6: !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>):
    %7 = "tpu_schedule.alloc"() <{role = "query_tile"}> : () -> !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>
    %8 = "tpu_schedule.alloc"() <{role = "relative_bias"}> : () -> !tpu_schedule.buffer<memref<4x128xbf16>, #tpu_schedule.shape<["H", "L"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>
    %9 = "tpu_schedule.alloc"() <{role = "attention_output"}> : () -> !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>
    %10 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %11 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %12 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %13 = "tpu_schedule.dma_start"(%0, %7, %10) <{stage = #builtin.int<0>}> : (!tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    %14 = "tpu_schedule.dma_start"(%5, %8, %11) <{stage = #builtin.int<0>}> : (!tpu_schedule.buffer<memref<4x128xbf16>, #tpu_schedule.shape<["H", "L"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4x128xbf16>, #tpu_schedule.shape<["H", "L"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    "tpu_schedule.dma_wait"(%13) <{stage = #builtin.int<1>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.dma_wait"(%14) <{stage = #builtin.int<1>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.ragged_paged_attention"(%7, %1, %2, %3, %4, %8, %9) <{stage = #builtin.int<2>, query_block_size = #builtin.int<1>, kv_block_size = #builtin.int<8>}> : (!tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.buffer<memref<32x16x4x32xbf16>, #tpu_schedule.shape<["P", "S", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>, #builtin.int<3>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<32x16x4x32xbf16>, #tpu_schedule.shape<["P", "S", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>, #builtin.int<3>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4x8xi32>, #tpu_schedule.shape<["B", "MP"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4xi32>, #tpu_schedule.shape<["B"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<[""]>, #tpu_schedule.layout<[#builtin.int<0>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4x128xbf16>, #tpu_schedule.shape<["H", "L"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>) -> ()
    %15 = "tpu_schedule.dma_start"(%9, %6, %12) <{stage = #builtin.int<3>}> : (!tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<4x4x32xbf16>, #tpu_schedule.shape<["B", "H", "D"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", "", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>, #builtin.int<2>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    "tpu_schedule.dma_wait"(%15) <{stage = #builtin.int<4>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.yield"() : () -> ()
  }) : () -> ()
}) : () -> ()
