"builtin.module"() ({
  "tpu_schedule.kernel"() <{sym_name = "matmul_16x32x16", target = "tpu7x", vmem_capacity_bytes = #builtin.int<1048576>, smem_capacity_bytes = #builtin.int<65536>}> ({
  ^bb0(%0: !tpu_schedule.buffer<memref<16x32xbf16>, #tpu_schedule.shape<["M", "K"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %1: !tpu_schedule.buffer<memref<32x16xbf16>, #tpu_schedule.shape<["K", "N"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, %2: !tpu_schedule.buffer<memref<16x16xf32>, #tpu_schedule.shape<["M", "N"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>):
    %3 = "tpu_schedule.alloc"() <{role = "lhs_tile"}> : () -> !tpu_schedule.buffer<memref<16x32xbf16>, #tpu_schedule.shape<["M", "K"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>
    %4 = "tpu_schedule.alloc"() <{role = "rhs_tile"}> : () -> !tpu_schedule.buffer<memref<32x16xbf16>, #tpu_schedule.shape<["K", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>
    %5 = "tpu_schedule.alloc"() <{role = "accumulator"}> : () -> !tpu_schedule.buffer<memref<16x16xf32>, #tpu_schedule.shape<["M", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>
    %6 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %7 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %8 = "tpu_schedule.semaphore_alloc"() : () -> !tpu_schedule.semaphore
    %9 = "tpu_schedule.dma_start"(%0, %3, %6) <{stage = #builtin.int<0>}> : (!tpu_schedule.buffer<memref<16x32xbf16>, #tpu_schedule.shape<["M", "K"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<16x32xbf16>, #tpu_schedule.shape<["M", "K"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    %10 = "tpu_schedule.dma_start"(%1, %4, %7) <{stage = #builtin.int<0>}> : (!tpu_schedule.buffer<memref<32x16xbf16>, #tpu_schedule.shape<["K", "N"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<32x16xbf16>, #tpu_schedule.shape<["K", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    "tpu_schedule.dma_wait"(%9) <{stage = #builtin.int<1>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.dma_wait"(%10) <{stage = #builtin.int<1>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.mxu_matmul"(%3, %4, %5) <{stage = #builtin.int<2>}> : (!tpu_schedule.buffer<memref<16x32xbf16>, #tpu_schedule.shape<["M", "K"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.buffer<memref<32x16xbf16>, #tpu_schedule.shape<["K", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<2>>>, !tpu_schedule.buffer<memref<16x16xf32>, #tpu_schedule.shape<["M", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>) -> ()
    %11 = "tpu_schedule.dma_start"(%5, %2, %8) <{stage = #builtin.int<3>}> : (!tpu_schedule.buffer<memref<16x16xf32>, #tpu_schedule.shape<["M", "N"]>, #tpu_schedule<memory_space vmem>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership kernel>, #tpu_schedule.lifetime<#builtin.int<2>, #builtin.int<4>>>, !tpu_schedule.buffer<memref<16x16xf32>, #tpu_schedule.shape<["M", "N"]>, #tpu_schedule<memory_space hbm>, #tpu_schedule.sharding<["", ""]>, #tpu_schedule.layout<[#builtin.int<0>, #builtin.int<1>]>, #tpu_schedule<ownership external>, #tpu_schedule.lifetime<#builtin.int<0>, #builtin.int<4>>>, !tpu_schedule.semaphore) -> !tpu_schedule.dma_token
    "tpu_schedule.dma_wait"(%11) <{stage = #builtin.int<4>}> : (!tpu_schedule.dma_token) -> ()
    "tpu_schedule.yield"() : () -> ()
  }) : () -> ()
}) : () -> ()
